config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :start_date, :end_date, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :name, :category, :description, :price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
                  against: [:name, :category],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_product, only: %i[new create]
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @booking.product = @product
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.product = @product
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:query].present?
      # sql_query = "name @@ :query OR category @@ :query"
      # @products = Product.where(sql_query, query: "%#{params[:query]}%")
      @products = Product.search_by_name_and_category(params[:query])
    else
      @products = Product.all
    end

  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params_product)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(params_product)
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def params_product
    params.require(:product).permit(:name, :category, :description, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
<h1><strong>My bookings</strong></h1>

<div class="card-small">
      <% @bookings.each do |booking|%>
        <div class='card'>
          <%# add link %>
            <a href="/bookings/<%=booking.id %>">
            <div class="card-img-top">
            <% if booking.product.photo.attached?%>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path booking.product.photo.key, height: 400, crop: :fill %>')">
              </div>
            <% end %>
            </div>

            <div class="card-body">
              <div class="card-text">
                <%# <div class="card-info d-flex justify-content-between"> %>
                  <div>
                    <p>
                      <strong>From:</strong> <%= booking.start_date.day %>
                       /<%= booking.start_date.month %>
                       /<%= booking.start_date.year %>
                    </p>
                  </div>
                  <div>
                    <p>
                      <strong>Until:</strong> <%= booking.end_date.day %>
                      /<%= booking.end_date.month %>
                      /<%= booking.end_date.year %>
                    </p>
                  </div>
                <%# </div> %>
              </div>
            </div>
          </a>
      </div>
      <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="d-flex justify-content-sm-center">
    <h1>When do you want to book <strong><%= @product.name %></strong>? </h1>
  </div>

    <div class="col-lg-6 mx-auto">
      <div class="form-boxes">
        <%= simple_form_for [@product, @booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true  %>
          <%= f.input :end_date, as: :date, html5: true %>
          <div class="d-flex flex-row-reverse">
            <%= f.submit "Book now!", class:"btn btn-dark" %>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="container text-center">

  <div class="d-flex justify-content-sm-center">
    <h1>You've booked <strong><%=@booking.product.name  %></strong>!</h1>
  </div>
  <div class="card-show" >
    <div class="col-lg-6 mx-auto">
      <div class= "card">
        <div class="card-img-top">
          <% if @booking.product.photo.attached? %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @booking.product.photo.key, height: 300, crop: :fill %>')">
            </div>
          <% end %>
        </div>

        <p>
          <strong>From:</strong> <%= @booking.start_date.day %>
          /<%= @booking.start_date.month %>
          /<%= @booking.start_date.year %>
        </p>
        <p>
          <strong>Until:</strong> <%= @booking.end_date.day %>
          /<%= @booking.end_date.month %>
          /<%= @booking.end_date.year %>
        </p>
      </div>
    </div>

      <div class="button mt-2">
        <%= link_to "Looking for more stuff?", products_path, class:"btn btn-dark"%>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsShare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="flex-grow-1">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-background">
  <div class="container">
    <div class="row align-items-center">
      <div class="col">
        <h4>welcome to <%= image_tag("sharelogo.png", :width => 200)%></h4>
        <p>A place where you can share your tool and make some profit of it or,
        to just rent it and save money.</p>
        <div class="order-1 p-2">
          <%# <%= link_to "Let's start", products_path, class:"btn btn-dark" %>
        </div>
          <div>
            <%= form_with url: products_path, method: :get, class: "d-flex" do %>
              <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "What are you looking for?"
              %>
              <%= submit_tag "Search", class: "btn btn-dark", id:"btn-search-index" %>
              <%= link_to "All products", products_path, class:"btn" %>
            <% end %>
          </div>
      </div>
      <div class="col">
        <img class="card-img" src="https://i.ibb.co/ScVYw65/Dise-o-sin-t-tulo.png" alt="Card image">
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container py-5">
  <%# <div class="col-lg-4 mx-auto"> %>
  <div class="d-flex justify-content-sm-center">
    <h1 >Edit your <strong>Product</strong> !</h1>
    <h2></h2>
  </div>

  <%# <div class="row" > %>
    <div class="col-lg-6 mx-auto">
      <%# <div class="card"> %>
        <div class="">
          <ul class="form-boxes">
            <%= simple_form_for @product do |f| %>
              <%= f.input :name, placeholder:"..." %>
              <%= f.input :category, placeholder:"..." %>
              <%= f.input :description, placeholder:"..." %>
              <%= f.input :price, placeholder:"€/hr" %>
              <%= f.input :photo, as: :file %>
              <div class="d-flex flex-row-reverse">
                <%= f.submit "Change", class:"btn btn-dark" %>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="header d-flex justify-content-between ">
    <div>
      <h1>All Products</h1>
    </div>

    <div>
      <%= form_with url: products_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Looking for something?"
        %>
        <%= submit_tag "Search", class: "btn btn-dark", id:"btn-search-index" %>
        <% end %>
    </div>
  </div>

  <div class="card-small">
      <% @products.each do |product|%>
        <div class='card list-group-item-action '>
          <a href="/products/<%=product.id %>">

            <div class="card-img-top">
            <% if product.photo.attached? %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path product.photo.key, height: 400, crop: :fill %>')">
              </div>
            <% end %>
            </div>

            <div class="card-body">
              <div class="card-text">
                <div class="card-info d-flex justify-content-between">
                  <div>
                    <h5><%= product.name.capitalize%></h3>
                  </div>
                  <div>
                    <p><%=  product.price %>€/day</p>
                  </div>
                </div>
                <p><%= product.description.first(50)%> ...</p>
              </div>
            </div>
          </a>
      </div>
      <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container py-5">
  <%# <div class="col-lg-4 mx-auto"> %>
  <div class="d-flex justify-content-sm-center">
    <h1 >New product? <strong>Share</strong> it!</h1>
    <h2></h2>
  </div>

  <%# <div class="row" > %>
    <div class="col-lg-6 mx-auto">
      <%# <div class="card"> %>
        <div class="">
          <ul class="form-boxes">
            <%= simple_form_for @product do |f| %>
              <%= f.input :name, placeholder:"Surf board" %>
              <%= f.input :category, placeholder:"Sports" %>
              <%= f.input :description, placeholder:"The fish" %>
              <%= f.input :price, placeholder:"€/day" %>
              <%= f.input :photo, as: :file %>
              <%# <% url_mapbox = "pk.eyJ1IjoibnJvdWdlciIsImEiOiJjbGEya3d4amUwaHNvM3NwazRsbWVkN2pkIn0.604LgsXW7i9RDHwzT61V5Q" %>
              <%# <%= f.input :address, %>
                <%# # input_html: {data: {address_autocomplete_target: "address"}}, %>
                <%# # wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV[url_mapbox]}} %>
              <div class="d-flex flex-row-reverse">
                <%= f.submit "Create", class:"btn btn-dark" %>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row card-big  d-flex justify-content-between">
    <div class="card-big-img col-6">
      <% if @product.photo.attached? %>
      <div class="card-category shadow" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path @product.photo.key, height: 1000, crop: :fill %>')">
      </div>
      <% end %>
    </div>

    <div class="card-big-info d-flex flex-column col-6">
      <div class="card-product d-flex justify-content-between m-2">
        <div class="title">
          <h1><%= @product.name.upcase %></h2>
          <h4><strong><%= @product.category.capitalize %></strong></p>
        </div>

        <div class="price d-flex align-items-center">
          <p><%= @product.price  %>€/day</p>
        </div>
      </div>

      <div class="description flex-grow-1 m-2">
        <p>Description:<%= @product.description.capitalize %></p>
      </div>

      <div class="big-car-link">
        <%= link_to "Edit", edit_product_path, class:"btn btn-dark btn-lg" %>
        <%= link_to "Delete", product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-dark btn-lg" %>
        <%= link_to "Book", new_product_booking_path(@product), class:" btn btn-dark btn-lg"%>
      </div>
    </div>
  </div>
</div>
<%# test %>

app/views/shared/_footer.html.erb
<div class="footer-basic">
  <footer>
    <div class="social">
      <a href="#"><i class="icon ion-social-instagram"></i></a>
      <a href="#"><i class="icon ion-social-snapchat"></i></a>
      <a href="#"><i class="icon ion-social-twitter"></i></a>
      <a href="#"><i class="icon ion-social-facebook"></i></a>
    </div>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Home</a></li>
      <li class="list-inline-item"><a href="#">Services</a></li>
      <li class="list-inline-item"><a href="#">About</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
    </ul>
    <p class="copyright">Make It Easy 2022</p>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon position-sticky top-0" id="navbar">
  <div class="container-fluid">
    <div class="type">
    <span data-controller="navbar-js"></span>

      <p><span class="logo-type" data-controller="typed-js" style="font-weight: bold; font-size: x-large;"></span></p>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
          <% name_size = current_user.email.index("@") %>
            <%= link_to "Welcome! #{current_user.email.capitalize.first(name_size)}", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
          </li>
          <li class="nav-item">
          </li>

            <%= image_tag "https://i.ibb.co/Gt89WsW/Negative0-34-34-1.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", products_path, class:"dropdown-item nav-link"%>
              <%= link_to "Add a new product", new_product_path, class:"dropdown-item nav-link"%>
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item nav-link" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item nav-link" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>